# https://github.com/google-github-actions/setup-gcloud/blob/master/example-workflows/cloud-run/cloud-run.yml
# https://cloud.google.com/sdk/gcloud/reference/run/deploy
on:
  push:
    branches:
    - main
    
name: Build Container
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build Dockerfile
      run: |-
        docker build -t ghcr.io/damiaocastro/webhook-to-pubsub:latest .
        docker push ghcr.io/damiaocastro/webhook-to-pubsub:latest

